### PR TITLE
minor change to get the "total" items with reviews, videos, news etc...

### PR DESCRIPTION
**Pull request by ayhid**
returning raw response for some methods , so one could add pagination logic

### CODE REVIEW

**Comment by bshaffer** [comment]
This is a very valid change.  I'm worried about it breaking backwards compatibility though.  Also, there are other APIs that may need to be changed as well.  We need to revise those, and make changes to all APIs at once if we are to use this convention.

I was afraid this day would come...

Thanks for your contribution!

**Comment by ayhid** [comment]
Hey thanks for the anwser, we might do somthin like this https://gist.github.com/60af5845a9709cc016bd

**Comment by bshaffer** [comment]
Yeah.  I would even argue it would be better to pass a setting to the API, as in `$echonest->getArtistApi($raw = true);`

**Comment by bshaffer** [comment]
Implemented the above solution.  See the `Response` section of the readme for an explanation.

I think if i ever make a PHP5.3 version, or if I just feel like it, I might update the API to return the full response every time.  What do you think?

**Comment by ayhid** [comment]
I think that make sense, if you need with that don't hesitate, I'll be happy to contribute

**Pull request closed without merging**
